//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHP()
        {
            this.KetQuaLopHPs = new HashSet<KetQuaLopHP>();
        }
    
        public string IDLopHP { get; set; }
        public string PhongHoc { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public Nullable<int> TongSoSV { get; set; }
        public string IDHocPhan { get; set; }
        public string IDHocKy { get; set; }
        public string IDGV { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaLopHP> KetQuaLopHPs { get; set; }
    }
}
