//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiemSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDiemSVCon : DbContext
    {
        public QLDiemSVCon()
            : base("name=QLDiemSVCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<HocPhan> HocPhans { get; set; }
        public virtual DbSet<KetQuaLopHP> KetQuaLopHPs { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<LopHP> LopHPs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TongKetKy> TongKetKies { get; set; }
    
        public virtual ObjectResult<viewDiemLHP_Result> viewDiemLHP(string iDLHP)
        {
            var iDLHPParameter = iDLHP != null ?
                new ObjectParameter("IDLHP", iDLHP) :
                new ObjectParameter("IDLHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDiemLHP_Result>("viewDiemLHP", iDLHPParameter);
        }
    
        public virtual int insertDHP(string iDSV, string iDLHP, Nullable<double> diemCC, Nullable<double> diemTX, Nullable<double> diemThi)
        {
            var iDSVParameter = iDSV != null ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(string));
    
            var iDLHPParameter = iDLHP != null ?
                new ObjectParameter("IDLHP", iDLHP) :
                new ObjectParameter("IDLHP", typeof(string));
    
            var diemCCParameter = diemCC.HasValue ?
                new ObjectParameter("diemCC", diemCC) :
                new ObjectParameter("diemCC", typeof(double));
    
            var diemTXParameter = diemTX.HasValue ?
                new ObjectParameter("diemTX", diemTX) :
                new ObjectParameter("diemTX", typeof(double));
    
            var diemThiParameter = diemThi.HasValue ?
                new ObjectParameter("diemThi", diemThi) :
                new ObjectParameter("diemThi", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertDHP", iDSVParameter, iDLHPParameter, diemCCParameter, diemTXParameter, diemThiParameter);
        }
    
        public virtual ObjectResult<viewHB_Result> viewHB(string iDHK)
        {
            var iDHKParameter = iDHK != null ?
                new ObjectParameter("IDHK", iDHK) :
                new ObjectParameter("IDHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewHB_Result>("viewHB", iDHKParameter);
        }
    
        public virtual ObjectResult<viewWithClass_Result> viewWithClass(string iDL)
        {
            var iDLParameter = iDL != null ?
                new ObjectParameter("IDL", iDL) :
                new ObjectParameter("IDL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewWithClass_Result>("viewWithClass", iDLParameter);
        }
    
        public virtual ObjectResult<viewProfile_Result> viewProfile(string iDSV)
        {
            var iDSVParameter = iDSV != null ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProfile_Result>("viewProfile", iDSVParameter);
        }
    
        public virtual int delSV(string iDSV)
        {
            var iDSVParameter = iDSV != null ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delSV", iDSVParameter);
        }
    
        public virtual int updSV(string iDSV, string ten, string iDL, Nullable<System.DateTime> nS, string gT)
        {
            var iDSVParameter = iDSV != null ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var iDLParameter = iDL != null ?
                new ObjectParameter("IDL", iDL) :
                new ObjectParameter("IDL", typeof(string));
    
            var nSParameter = nS.HasValue ?
                new ObjectParameter("NS", nS) :
                new ObjectParameter("NS", typeof(System.DateTime));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updSV", iDSVParameter, tenParameter, iDLParameter, nSParameter, gTParameter);
        }
    
        public virtual int addSV(string iDSV, string ten, string iDL, Nullable<System.DateTime> nS, string gT)
        {
            var iDSVParameter = iDSV != null ?
                new ObjectParameter("IDSV", iDSV) :
                new ObjectParameter("IDSV", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var iDLParameter = iDL != null ?
                new ObjectParameter("IDL", iDL) :
                new ObjectParameter("IDL", typeof(string));
    
            var nSParameter = nS.HasValue ?
                new ObjectParameter("NS", nS) :
                new ObjectParameter("NS", typeof(System.DateTime));
    
            var gTParameter = gT != null ?
                new ObjectParameter("GT", gT) :
                new ObjectParameter("GT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSV", iDSVParameter, tenParameter, iDLParameter, nSParameter, gTParameter);
        }
    
        public virtual ObjectResult<viewCCHT_Result> viewCCHT(string iDHK)
        {
            var iDHKParameter = iDHK != null ?
                new ObjectParameter("IDHK", iDHK) :
                new ObjectParameter("IDHK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewCCHT_Result>("viewCCHT", iDHKParameter);
        }
    
        public virtual ObjectResult<viewHP_Result> viewHP(string iDHP)
        {
            var iDHPParameter = iDHP != null ?
                new ObjectParameter("IDHP", iDHP) :
                new ObjectParameter("IDHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewHP_Result>("viewHP", iDHPParameter);
        }
    
        public virtual int updLHP(string iDLHP, string iDHP, string hk, Nullable<System.DateTime> ngayThi, string pH, string iDGV)
        {
            var iDLHPParameter = iDLHP != null ?
                new ObjectParameter("IDLHP", iDLHP) :
                new ObjectParameter("IDLHP", typeof(string));
    
            var iDHPParameter = iDHP != null ?
                new ObjectParameter("IDHP", iDHP) :
                new ObjectParameter("IDHP", typeof(string));
    
            var hkParameter = hk != null ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(string));
    
            var ngayThiParameter = ngayThi.HasValue ?
                new ObjectParameter("NgayThi", ngayThi) :
                new ObjectParameter("NgayThi", typeof(System.DateTime));
    
            var pHParameter = pH != null ?
                new ObjectParameter("PH", pH) :
                new ObjectParameter("PH", typeof(string));
    
            var iDGVParameter = iDGV != null ?
                new ObjectParameter("IDGV", iDGV) :
                new ObjectParameter("IDGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updLHP", iDLHPParameter, iDHPParameter, hkParameter, ngayThiParameter, pHParameter, iDGVParameter);
        }
    
        public virtual int addLHP(string iDLHP, string iDHP, string hk, Nullable<System.DateTime> ngayThi, string pH, string iDGV)
        {
            var iDLHPParameter = iDLHP != null ?
                new ObjectParameter("IDLHP", iDLHP) :
                new ObjectParameter("IDLHP", typeof(string));
    
            var iDHPParameter = iDHP != null ?
                new ObjectParameter("IDHP", iDHP) :
                new ObjectParameter("IDHP", typeof(string));
    
            var hkParameter = hk != null ?
                new ObjectParameter("hk", hk) :
                new ObjectParameter("hk", typeof(string));
    
            var ngayThiParameter = ngayThi.HasValue ?
                new ObjectParameter("NgayThi", ngayThi) :
                new ObjectParameter("NgayThi", typeof(System.DateTime));
    
            var pHParameter = pH != null ?
                new ObjectParameter("PH", pH) :
                new ObjectParameter("PH", typeof(string));
    
            var iDGVParameter = iDGV != null ?
                new ObjectParameter("IDGV", iDGV) :
                new ObjectParameter("IDGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addLHP", iDLHPParameter, iDHPParameter, hkParameter, ngayThiParameter, pHParameter, iDGVParameter);
        }
    
        public virtual int delLHP(string iDLHP)
        {
            var iDLHPParameter = iDLHP != null ?
                new ObjectParameter("IDLHP", iDLHP) :
                new ObjectParameter("IDLHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delLHP", iDLHPParameter);
        }
    
        public virtual ObjectResult<viewSTPrInLHP_Result> viewSTPrInLHP(string maLHP)
        {
            var maLHPParameter = maLHP != null ?
                new ObjectParameter("MaLHP", maLHP) :
                new ObjectParameter("MaLHP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewSTPrInLHP_Result>("viewSTPrInLHP", maLHPParameter);
        }
    }
}
